# -*- coding: utf-8 -*-
"""Copy of LINER REGRESSION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cED6xOWtr4PKl9agsAXs_Cu0VZPgeREZ
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

file_path = 'salesprojectdataset.csv'
# Read the CSV file using the full file path
data = pd.read_csv("salesprojectdataset.csv")

data

print("Missing values:")
print(data.isnull().sum())

data.dropna(inplace=False)

data.dropna(inplace=True)

selected_features=['Item_Weight','Outlet_Years']

X=data[selected_features]
y= data['Item_MRP']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=40)

Le = LabelEncoder()
data["Item_MRP"] = Le.fit_transform(data["Item_MRP"])

model= LinearRegression()
model.fit(X_train,y_train)

y_pred =model.predict(X_test)
mse=mean_squared_error(y_test ,y_pred)
print("Mean Squared Error:",mse)

import matplotlib.pyplot as plt

plt.scatter(y_test,y_pred)
plt.xlabel("Item_Weight")
plt.ylabel("Item_MRP")
plt.title("sales prediction")
plt.show()

import pickle
pickle.dump(model,open('model.pkl','wb'))